### ISSUE TITLE
Natives fail to load

### ISSUE THREAD

**Issue by joshuafhiggins** [LabyMod/ultralight-java#71]
When following the examples, Java throws an UnsatisfiedLinkError when trying to load libUltralightCore. I'm properly setting the java.library.path to also have the Ultralight bin files. I have no idea why it isn't working and have tried my best to follow it in debug mode. This also occurs on both Linux and Windows and I don't know about macOS

Here's the full expection:
```
Exception in thread "main" java.lang.RuntimeException: Failed to load ultralight-java-gpu native library.
	at com.labymedia.ultralight.gpu.UltralightGPUDriverNativeUtil.load(UltralightGPUDriverNativeUtil.java:141)
	at me.toast.engine.ui.UserInterface.<init>(UserInterface.java:62)
	at me.toast.engine.Mod.<init>(Mod.java:41)
	at test.game.DeathmatchMod.<init>(DeathmatchMod.java:19)
	at me.toast.engine.Main.run(Main.java:13)
	at me.toast.engine.Main.main(Main.java:42)
Caused by: java.lang.UnsatisfiedLinkError: /home/joshuahiggins/Documents/GitHub/ButterEngine/bin/libultralight-java-gpu.so: libUltralightCore.so: cannot open shared object file: No such file or directory
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2383)
	at java.base/java.lang.Runtime.load0(Runtime.java:746)
	at java.base/java.lang.System.load(System.java:1857)
	at com.labymedia.ultralight.gpu.UltralightGPUDriverNativeUtil.load(UltralightGPUDriverNativeUtil.java:139)
	... 5 more
```

Here's my code for starting Ultralight:

```
        Path nativesDir = Paths.get("bin/");

        String libraryPath = System.getProperty("java.library.path");
        if (libraryPath != null) {
            libraryPath += File.pathSeparator + nativesDir.toAbsolutePath();
        } else {
            libraryPath = nativesDir.toAbsolutePath().toString();
        }

        System.setProperty("java.library.path", libraryPath);

        try {
            UltralightGPUDriverNativeUtil.extractNativeLibrary(nativesDir);
            UltralightJava.extractNativeLibrary(nativesDir);

            UltralightGPUDriverNativeUtil.load(nativesDir);
            UltralightJava.load(nativesDir);
        } catch (UltralightLoadException e) {
            e.printStackTrace();
        }
```

Here's the tree of my project:

```
.
├── bin
│   ├── AppCore.dll
│   ├── libAppCore.dylib
│   ├── libAppCore.so
│   ├── libUltralightCore.dylib
│   ├── libUltralightCore.so
│   ├── libUltralight.dylib
│   ├── libultralight-java-gpu.so
│   ├── libultralight-java.so
│   ├── libUltralight.so
│   ├── libWebCore.dylib
│   ├── libWebCore.so
│   ├── resources
│   │   ├── cacert.pem
│   │   └── icudt67l.dat
│   ├── UltralightCore.dll
│   ├── Ultralight.dll
│   └── WebCore.dll
├── libs
│   ├── ...
│   ├── ultralight-java-base-0.4.12.jar
│   ├── ultralight-java-base-0.4.12-javadoc.jar
│   ├── ultralight-java-base-0.4.12-sources.jar
│   ├── ultralight-java-databind-0.4.12.jar
│   ├── ultralight-java-databind-0.4.12-javadoc.jar
│   ├── ultralight-java-databind-0.4.12-sources.jar
│   ├── ultralight-java-gpu-0.4.12.jar
│   ├── ultralight-java-gpu-0.4.12-javadoc.jar
│   ├── ultralight-java-gpu-0.4.12-sources.jar
│   └── ...
├── out
│   └── ...
├── resources
│   ├── assets
│   │   └── ...
│   ├── example.html
│   ├── example.js
│   ├── shader_fill_frag.fs
│   ├── shader_fill_path_frag.fs
│   ├── shader_v2f_c4f_t2f_t2f_d28f.vs
│   ├── shader_v2f_c4f_t2f.vs
│   └── style.css
└── src
    └── ...
````

**Comment by joshuafhiggins** [comment]
I have changed natives to the b8daecd branch, and it still fails on Windows with:
```
Exception in thread "main" java.lang.RuntimeException: Failed to load ultralight-java-gpu native library.
	at com.labymedia.ultralight.gpu.UltralightGPUDriverNativeUtil.load(UltralightGPUDriverNativeUtil.java:141)
	at me.toast.engine.ui.UserInterface.<init>(UserInterface.java:41)
	at me.toast.engine.Mod.<init>(Mod.java:41)
	at test.game.DeathmatchMod.<init>(DeathmatchMod.java:19)
	at me.toast.engine.Main.run(Main.java:13)
	at me.toast.engine.Main.main(Main.java:42)
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\Joshua\Documents\GitHub\ButterEngine\bin\ultralight-java-gpu.dll: Can't find dependent libraries
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2383)
	at java.base/java.lang.Runtime.load0(Runtime.java:746)
	at java.base/java.lang.System.load(System.java:1857)
	at com.labymedia.ultralight.gpu.UltralightGPUDriverNativeUtil.load(UltralightGPUDriverNativeUtil.java:139)
	... 5 more
```
I have tried to manually set the PATH variable to have the bin/ folder in it but it still fails with this.

On Linux it gives a similar error:
```
Exception in thread "main" java.lang.RuntimeException: Failed to load ultralight-java-gpu native library.
	at com.labymedia.ultralight.gpu.UltralightGPUDriverNativeUtil.load(UltralightGPUDriverNativeUtil.java:141)
	at me.toast.engine.ui.UserInterface.<init>(UserInterface.java:35)
	at me.toast.engine.Mod.<init>(Mod.java:41)
	at test.game.DeathmatchMod.<init>(DeathmatchMod.java:19)
	at me.toast.engine.Main.run(Main.java:13)
	at me.toast.engine.Main.main(Main.java:42)
Caused by: java.lang.UnsatisfiedLinkError: /home/joshuahiggins/Documents/GitHub/ButterEngine/bin/libultralight-java-gpu.so: libUltralightCore.so: cannot open shared object file: No such file or directory
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2383)
	at java.base/java.lang.Runtime.load0(Runtime.java:746)
	at java.base/java.lang.System.load(System.java:1857)
	at com.labymedia.ultralight.gpu.UltralightGPUDriverNativeUtil.load(UltralightGPUDriverNativeUtil.java:139)
	... 5 more
```

**Comment by joshuafhiggins** [comment]
I have gotten a bit further now. The game no longer crashes out right and proceeds like normal but a different exception is thrown if I load the GPU driver after Ultralight. (Different from the example)
Before:
```
        try {
            UltralightGPUDriverNativeUtil.extractNativeLibrary(nativesDir);
            UltralightJava.extractNativeLibrary(nativesDir);

            UltralightGPUDriverNativeUtil.load(nativesDir);
            UltralightJava.load(nativesDir);
        } catch (UltralightLoadException e) {
            e.printStackTrace();
        }
```
After:
```
        try {
            UltralightJava.extractNativeLibrary(nativesDir);
            UltralightGPUDriverNativeUtil.extractNativeLibrary(nativesDir);

            UltralightJava.load(nativesDir);
            UltralightGPUDriverNativeUtil.load(nativesDir);
        } catch (UltralightLoadException e) {
            e.printStackTrace();
        }
```
The new execption:
```
OpenJDK 64-Bit Server VM warning: You have loaded library /home/joshuahiggins/Documents/GitHub/ButterEngine/bin/libWebCore.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
com.labymedia.ultralight.UltralightLoadException: Failed to load native dependency WebCore (tried to load from bin/libWebCore.so)
	at com.labymedia.ultralight.UltralightJava.load(UltralightJava.java:146)
	at com.labymedia.ultralight.UltralightJava.load(UltralightJava.java:115)
	at me.toast.engine.ui.UserInterface.<init>(UserInterface.java:35)
	at me.toast.engine.Mod.<init>(Mod.java:41)
	at test.game.DeathmatchMod.<init>(DeathmatchMod.java:19)
	at me.toast.engine.Main.run(Main.java:13)
	at me.toast.engine.Main.main(Main.java:42)
Caused by: java.lang.UnsatisfiedLinkError: /home/joshuahiggins/Documents/GitHub/ButterEngine/bin/libWebCore.so: /home/joshuahiggins/Documents/GitHub/ButterEngine/bin/libglib-2.0.so.0: file too short
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2383)
	at java.base/java.lang.Runtime.load0(Runtime.java:746)
	at java.base/java.lang.System.load(System.java:1857)
	at com.labymedia.ultralight.UltralightJava.load(UltralightJava.java:144)
	... 6 more
```

**Comment by joshuafhiggins** [comment]
Using the Maven bindings build, with the latest SDK being v1.2.1, and switching the order of those lines causes no errors except for WebCore not having stack guard but the JVM fixes it on the fly.
